<?php

declare(strict_types=1);

/*
 * This file is part of TYPO3 CMS-based extension "aim" by b13.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 */

namespace B13\Aim\Prompt;

/**
 * Who produced an auto-detected tone-of-voice fragment.
 *
 *  - Cli:    aim's own aim:calibrateVoice command.
 *  - Upload: a consumer's own feature (e.g. EXT:t3ppy's Brain module).
 */
enum AutoGeneratedFragmentSource: string
{
    case Cli = 'cli';
    case Upload = 'upload';
}
