<?php

declare(strict_types=1);

/*
 * This file is part of TYPO3 CMS-based extension "aim" by b13.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 */

namespace B13\Aim\Service;

use B13\Aim\Domain\Model\FragmentAssignmentCounts;
use B13\Aim\Domain\Model\PageFragmentAssignmentInfo;
use B13\Aim\Domain\Model\ToneOfVoiceInfo;
use B13\Aim\Domain\Repository\PagePromptFragmentRepository;
use B13\Aim\Prompt\AutoGeneratedFragmentSource;
use Symfony\Component\DependencyInjection\Attribute\Autoconfigure;
use TYPO3\CMS\Backend\Routing\UriBuilder;
use TYPO3\CMS\Backend\Utility\BackendUtility;
use TYPO3\CMS\Core\Localization\LanguageService;
use TYPO3\CMS\Core\Schema\SchemaLabelResolver;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * Public API for other extensions to read/write per-page prompt fragment
 * assignments and the tone-of-voice fragment, without reaching into aim's
 * own tables, repository, or route identifiers directly.
 *
 * Deliberately narrow: only what a consumer needs to display or maintain
 * this data from outside the Prompt Management module itself, not the
 * full PagePromptFragmentRepository surface (demand-based listing,
 * pagination, usage enrichment, ...), which stays that module's own
 * private concern.
 */
#[Autoconfigure(public: true)]
final class PromptManagementApi
{
    public function __construct(
        private readonly PagePromptFragmentRepository $fragmentRepository,
        private readonly UriBuilder $uriBuilder,
    ) {}

    /**
     * Fragments assigned directly on one specific page, not resolved/
     * inherited across the rootline.
     *
     * $returnUrl is where each fragment's own edit form should return to.
     *
     * @return list<PageFragmentAssignmentInfo>
     */
    public function findFragmentsForPage(int $pageId, string $returnUrl): array
    {
        $rows = $this->fragmentRepository->findAssignmentsForPage($pageId);

        return array_map(
            function (array $row) use ($returnUrl): PageFragmentAssignmentInfo {
                return new PageFragmentAssignmentInfo(
                    (int)$row['uid'],
                    (string)$row['title'],
                    $this->resolveScopeLabels((string)$row['scope']),
                    (bool)$row['inherit_to_subpages'],
                    $this->buildAssignmentEditUrl((int)$row['uid'], $returnUrl),
                );
            },
            $rows,
        );
    }

    /**
     * The single auto-detected tone-of-voice fragment for a site root
     * page, or null when none has been calibrated/uploaded yet.
     *
     * $returnUrl is where the fragment's own edit form should return to.
     */
    public function findToneOfVoice(int $rootPageId, string $returnUrl): ?ToneOfVoiceInfo
    {
        $row = $this->fragmentRepository->findAutoDetectedFragmentForRootPage($rootPageId);
        if ($row === null) {
            return null;
        }

        return new ToneOfVoiceInfo(
            (int)$row['uid'],
            (string)$row['title'],
            $row['auto_generated_source'] === AutoGeneratedFragmentSource::Cli->value,
            (string)$row['prompt'],
            (string)$row['examples'],
            $this->buildFragmentEditUrl((int)$row['uid'], $returnUrl),
        );
    }

    /**
     * Install-wide fragment assignment counts, for a summary/stats panel with no single page selected
     */
    public function countAllFragmentAssignments(): FragmentAssignmentCounts
    {
        $counts = $this->fragmentRepository->countAllAssignments();
        return new FragmentAssignmentCounts($counts['total'], $counts['inherited']);
    }

    /**
     * Saves an auto-detected tone-of-voice fragment for a site root page,
     * refreshing the existing one on a second call rather than creating a
     * duplicate. $source identifies the calling feature and drives
     * findToneOfVoice()'s own isCliCalibrated flag; it is not derived
     * from $title, which an editor remains free to rename afterward.
     *
     * @param list<string> $scope
     */
    public function saveAutoDetectedFragment(
        int $rootPageId,
        string $title,
        string $prompt,
        string $examples,
        array $scope,
        AutoGeneratedFragmentSource $source,
    ): int {
        return $this->fragmentRepository->upsertAutoDetectedFragment($rootPageId, $title, $prompt, $examples, $scope, $source);
    }

    /**
     * @param array<string, mixed> $parameters
     */
    public function buildPromptManagementUrl(array $parameters = []): string
    {
        return (string)$this->uriBuilder->buildUriFromRoute('aim_prompt_management', $parameters);
    }

    private function buildAssignmentEditUrl(int $assignmentUid, string $returnUrl): string
    {
        return (string)$this->uriBuilder->buildUriFromRoute('record_edit', [
            'edit' => ['tx_aim_page_prompt_fragment' => [$assignmentUid => 'edit']],
            'returnUrl' => $returnUrl,
        ]);
    }

    private function buildFragmentEditUrl(int $fragmentUid, string $returnUrl): string
    {
        return (string)$this->uriBuilder->buildUriFromRoute('record_edit', [
            'edit' => ['tx_aim_prompt_fragment' => [$fragmentUid => 'edit']],
            'returnUrl' => $returnUrl,
        ]);
    }

    /**
     * SchemaLabelResolver only exists from TYPO3 v14 on; use
     * BackendUtility::getLabelsFromItemsList() for v12/v13 as
     * equivalent. Both silently skip a value with no matching
     * item, including the literal "all" sentinel.
     *
     * @return list<string>
     */
    private function resolveScopeLabels(string $rawScope): array
    {
        if (class_exists(SchemaLabelResolver::class)) {
            $labelResolver = GeneralUtility::makeInstance(SchemaLabelResolver::class);
            $languageService = $this->getLanguageService();
            return array_map(
                $languageService->sL(...),
                $labelResolver->getLabelsForFieldValues('tx_aim_prompt_fragment', 'scope', $rawScope),
            );
        }

        $joinedLabels = BackendUtility::getLabelsFromItemsList('tx_aim_prompt_fragment', 'scope', $rawScope);
        return $joinedLabels === '' ? [] : GeneralUtility::trimExplode(',', $joinedLabels, true);
    }

    private function getLanguageService(): LanguageService
    {
        return $GLOBALS['LANG'];
    }
}
