<?php

declare(strict_types=1);

/*
 * This file is part of TYPO3 CMS-based extension "aim" by b13.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 */

namespace B13\Aim\Tests\Functional\Domain\Repository;

use B13\Aim\Domain\Repository\PagePromptFragmentDemand;
use B13\Aim\Domain\Repository\PagePromptFragmentRepository;
use B13\Aim\Prompt\AutoGeneratedFragmentSource;
use B13\Aim\Prompt\PromptFragmentScope;
use PHPUnit\Framework\Attributes\Test;
use TYPO3\CMS\Core\Database\Connection;
use TYPO3\TestingFramework\Core\Functional\FunctionalTestCase;

/**
 * Page tree used across these tests. tx_aim_prompt_fragment is a reusable
 * library entry with no page relation of its own; tx_aim_page_prompt_fragment
 * is the per-page assignment that carries `parent_page`:
 *
 *   1 "Has a text fragment"       -- assignment -> fragment: scope=text, prompt contains "banana"
 *   2 "Has an image fragment"     -- assignment -> fragment: scope=imageGeneration
 *   3 "No fragments"              -- no tx_aim_page_prompt_fragment rows at all
 *   4 "Two fragments"             -- two assignments (text + all) -- must appear exactly once
 *   5 "Multi-scope fragment"      -- one assignment -> fragment: scope=text,vision
 */
final class PagePromptFragmentRepositoryTest extends FunctionalTestCase
{
    protected array $testExtensionsToLoad = [
        'b13/aim',
    ];

    protected function setUp(): void
    {
        parent::setUp();

        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 1, 'pid' => 0, 'title' => 'Has a text fragment']);
        $pages->insert('pages', ['uid' => 2, 'pid' => 0, 'title' => 'Has an image fragment']);
        $pages->insert('pages', ['uid' => 3, 'pid' => 0, 'title' => 'No fragments']);
        $pages->insert('pages', ['uid' => 4, 'pid' => 0, 'title' => 'Two fragments']);
        $pages->insert('pages', ['uid' => 5, 'pid' => 0, 'title' => 'Multi-scope fragment']);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');

        $fragmentAUid = $this->insertFragment($fragments, 'Fragment A', 'Always mention the banana promotion.', PromptFragmentScope::Text->value);
        $this->insertAssignment($assignments, 1, $fragmentAUid);

        $fragmentBUid = $this->insertFragment($fragments, 'Fragment B', 'Add a watermark.', PromptFragmentScope::ImageGeneration->value);
        $this->insertAssignment($assignments, 2, $fragmentBUid);

        $fragmentC1Uid = $this->insertFragment($fragments, 'Fragment C1', 'Formal tone.', PromptFragmentScope::Text->value);
        // Sorting is deliberately reversed against title (C1 gets the
        // HIGHER sorting value) so a test asserting the title-alphabetical
        // order [C1, C2] and one asserting the actual assignment order
        // [C2, C1] can't be satisfied by the same, coincidentally-matching
        // fixture.
        $this->insertAssignment($assignments, 4, $fragmentC1Uid, 20);

        $fragmentC2Uid = $this->insertFragment($fragments, 'Fragment C2', 'Brand voice.', PromptFragmentScope::All->value);
        $this->insertAssignment($assignments, 4, $fragmentC2Uid, 10);

        $fragmentDUid = $this->insertFragment($fragments, 'Fragment D', 'Ask for both text and vision styling.', PromptFragmentScope::Text->value . ',' . PromptFragmentScope::Vision->value);
        $this->insertAssignment($assignments, 5, $fragmentDUid);
    }

    private function insertFragment(Connection $connection, string $title, string $prompt, string $scope): int
    {
        $connection->insert('tx_aim_prompt_fragment', [
            'pid' => 0,
            'title' => $title,
            'prompt' => $prompt,
            'scope' => $scope,
        ]);
        return (int)$connection->lastInsertId();
    }

    private function insertAssignment(Connection $connection, int $pageId, int $fragmentUid, int $sorting = 0): void
    {
        $connection->insert('tx_aim_page_prompt_fragment', [
            'pid' => $pageId,
            'parent_page' => $pageId,
            'fragment' => $fragmentUid,
            'sorting' => $sorting,
        ]);
    }

    private function repository(): PagePromptFragmentRepository
    {
        return $this->get(PagePromptFragmentRepository::class);
    }

    #[Test]
    public function onlyListsPagesThatHaveAtLeastOneFragment(): void
    {
        $rows = $this->repository()->findByDemand(new PagePromptFragmentDemand(), null);

        // Default sort is by title, ascending: "Multi-scope fragment" (5)
        // sorts before "Two fragments" (4).
        self::assertSame([1, 2, 5, 4], array_map(static fn(array $row): int => (int)$row['uid'], $rows));
    }

    #[Test]
    public function aPageWithMultipleFragmentsAppearsExactlyOnce(): void
    {
        $rows = $this->repository()->findByDemand(new PagePromptFragmentDemand(), null);

        $matchingPage4 = array_filter($rows, static fn(array $row): bool => (int)$row['uid'] === 4);
        self::assertCount(1, $matchingPage4);
    }

    #[Test]
    public function scopeFilterOnlyMatchesThatScopeOrAllScopeFragments(): void
    {
        $rows = $this->repository()->findByDemand(new PagePromptFragmentDemand(scope: PromptFragmentScope::ImageGeneration), null);

        // Page 2's fragment is imageGeneration-scoped; page 4's "Fragment C2"
        // is all-scoped, which must match every specific-scope filter too.
        self::assertSame([2, 4], array_map(static fn(array $row): int => (int)$row['uid'], $rows));
    }

    #[Test]
    public function searchMatchesPromptContent(): void
    {
        $rows = $this->repository()->findByDemand(new PagePromptFragmentDemand(search: 'banana'), null);

        self::assertSame([1], array_map(static fn(array $row): int => (int)$row['uid'], $rows));
    }

    #[Test]
    public function searchIsCaseAndWildcardSafe(): void
    {
        self::assertSame([], array_map(
            static fn(array $row): int => (int)$row['uid'],
            $this->repository()->findByDemand(new PagePromptFragmentDemand(search: 'nonexistent term'), null),
        ));
    }

    #[Test]
    public function anEmptyAccessiblePageIdListShortCircuitsToNoResultsWithoutQuerying(): void
    {
        self::assertSame([], $this->repository()->findByDemand(new PagePromptFragmentDemand(), []));
        self::assertSame(0, $this->repository()->countByDemand(new PagePromptFragmentDemand(), []));
    }

    /**
     * Regression test: unlike findByDemand()/countByDemand() above (the
     * Pages listing, where an empty accessible-id list genuinely means
     * "nothing to show"), the Library listing's own query builder always
     * OR's in `pid = 0` (global fragments) regardless of $accessiblePageIds
     * - matching the "pid=0 is always allowed" rule PromptFragmentSuggestReceiver
     * enforces for the suggest wizard. A restricted user with zero
     * accessible pages must still see every global fragment here; an early
     * `if ($accessiblePageIds === []) return [];` short-circuit would wrongly
     * hide them.
     */
    #[Test]
    public function anEmptyAccessiblePageIdListStillShowsGlobalFragmentsInTheLibrary(): void
    {
        // Every fixture fragment is created at pid=0 (see insertFragment()),
        // so all 5 must still be returned/counted even with zero accessible pages.
        self::assertCount(5, $this->repository()->findLibraryByDemand(new PagePromptFragmentDemand(), []));
        self::assertSame(5, $this->repository()->countLibraryByDemand(new PagePromptFragmentDemand(), []));
    }

    /**
     * Regression test: the Library listing used to have no page-tree
     * filtering at all - the fix adds $usagePageIds, a THIRD, separate
     * filter from the existing $accessiblePageIds access check. It answers
     * "is this fragment actually ASSIGNED somewhere in the selected
     * subtree", not "is this fragment's own storage pid one the user may
     * reach" (that remains $accessiblePageIds' job, entirely unaffected by
     * this fixture: every fragment here is stored at pid=0 regardless of
     * where it's assigned). A fragment assigned inside the subtree must
     * appear, one assigned only outside it must not, and a pid=0 fragment
     * with no assignment at all must appear regardless - global fragments
     * are exempt from tree filtering the same way they're exempt from the
     * accessible-pages check.
     */
    #[Test]
    public function findLibraryByDemandFiltersByUsageWithinTheGivenSubtreeNotByStoragePid(): void
    {
        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 100, 'pid' => 0, 'title' => 'Subtree root']);
        $pages->insert('pages', ['uid' => 101, 'pid' => 100, 'title' => 'Subtree child']);
        $pages->insert('pages', ['uid' => 200, 'pid' => 0, 'title' => 'Outside subtree']);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');

        // Stored at a non-zero, unrelated pid (300, not inserted as a real
        // page - fine, nothing dereferences a fragment's own storage pid as
        // a foreign key here): insertFragment() always uses pid=0, which is
        // unconditionally exempt from the usage filter and would make this
        // test pass regardless of whether the filter works at all.
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 300, 'title' => 'In-subtree fragment', 'prompt' => 'Tone.', 'scope' => 'all']);
        $inSubtreeUid = (int)$fragments->lastInsertId();
        $this->insertAssignment($assignments, 101, $inSubtreeUid);

        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 300, 'title' => 'Outside-subtree fragment', 'prompt' => 'Tone.', 'scope' => 'all']);
        $outsideSubtreeUid = (int)$fragments->lastInsertId();
        $this->insertAssignment($assignments, 200, $outsideSubtreeUid);

        $unassignedGlobalUid = $this->insertFragment($fragments, 'Unassigned global fragment', 'Tone.', PromptFragmentScope::All->value);

        $subtreePageIds = [100, 101];
        $rows = $this->repository()->findLibraryByDemand(new PagePromptFragmentDemand(), null, $subtreePageIds);
        $uids = array_map(static fn(array $row): int => (int)$row['uid'], $rows);

        self::assertContains($inSubtreeUid, $uids, 'A fragment assigned inside the selected subtree must appear.');
        self::assertNotContains($outsideSubtreeUid, $uids, 'A fragment assigned only outside the selected subtree must not appear.');
        self::assertContains($unassignedGlobalUid, $uids, 'An unassigned global fragment must appear regardless of tree selection.');

        self::assertSame(
            count($uids),
            $this->repository()->countLibraryByDemand(new PagePromptFragmentDemand(), null, $subtreePageIds),
            'countLibraryByDemand() must apply the identical usage filter.',
        );
    }

    /**
     * Regression test: a fragment STORED inside the selected subtree (its
     * own pid) but never actually ASSIGNED to any page there must NOT
     * appear once tree filtering is active - conflating "stored under this
     * page" with "used somewhere in this subtree" was the exact bug the
     * fix above avoids. This fragment's storage pid (101) is inside the
     * subtree, but its one real assignment (page 200) is not.
     */
    #[Test]
    public function findLibraryByDemandDoesNotMatchOnStoragePidAloneWhenFilteringByUsage(): void
    {
        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 100, 'pid' => 0, 'title' => 'Subtree root']);
        $pages->insert('pages', ['uid' => 101, 'pid' => 100, 'title' => 'Subtree child']);
        $pages->insert('pages', ['uid' => 200, 'pid' => 0, 'title' => 'Outside subtree']);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');

        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 101, 'title' => 'Stored inside, used outside', 'prompt' => 'Tone.', 'scope' => 'all']);
        $storedInsideUid = (int)$fragments->lastInsertId();
        $this->insertAssignment($assignments, 200, $storedInsideUid);

        $rows = $this->repository()->findLibraryByDemand(new PagePromptFragmentDemand(), null, [100, 101]);
        $uids = array_map(static fn(array $row): int => (int)$row['uid'], $rows);

        self::assertNotContains($storedInsideUid, $uids, 'Storage pid inside the subtree must not substitute for an actual usage there.');
    }

    #[Test]
    public function restrictsToTheGivenAccessiblePageIdsWhenNotNull(): void
    {
        $rows = $this->repository()->findByDemand(new PagePromptFragmentDemand(), [1, 3]);

        // Page 3 has no fragments so it's excluded regardless; page 1 is in
        // the accessible set and has a fragment, so it's included. Pages 2
        // and 4 are excluded purely by the accessible-id restriction.
        self::assertSame([1], array_map(static fn(array $row): int => (int)$row['uid'], $rows));
    }

    #[Test]
    public function nullAccessiblePageIdsMeansUnrestricted(): void
    {
        self::assertCount(4, $this->repository()->findByDemand(new PagePromptFragmentDemand(), null));
    }

    #[Test]
    public function countByDemandCountsDistinctPagesNotFragmentRows(): void
    {
        // Page 4 has two matching fragments, which must count as one page.
        self::assertSame(4, $this->repository()->countByDemand(new PagePromptFragmentDemand(), null));
    }

    #[Test]
    public function scopeFilterMatchesAFragmentThatListsTheRequestedCapabilityAmongSeveral(): void
    {
        $textRows = $this->repository()->findByDemand(new PagePromptFragmentDemand(scope: PromptFragmentScope::Text), null);
        // Page 5's fragment lists "text" among several capabilities. Default
        // sort is by title, ascending: "Multi-scope fragment" (5) sorts
        // before "Two fragments" (4).
        self::assertSame([1, 5, 4], array_map(static fn(array $row): int => (int)$row['uid'], $textRows));

        $visionRows = $this->repository()->findByDemand(new PagePromptFragmentDemand(scope: PromptFragmentScope::Vision), null);
        // Page 4's "Fragment C2" is all-scoped (matches every specific-scope
        // filter too); page 5's fragment lists "vision" among several.
        self::assertSame([5, 4], array_map(static fn(array $row): int => (int)$row['uid'], $visionRows));

        $translationRows = $this->repository()->findByDemand(new PagePromptFragmentDemand(scope: PromptFragmentScope::Translation), null);
        self::assertSame([4], array_map(static fn(array $row): int => (int)$row['uid'], $translationRows));
    }

    #[Test]
    public function enrichWithFragmentSummaryAddsCountAndDistinctScopesPerPage(): void
    {
        $rows = $this->repository()->findByDemand(new PagePromptFragmentDemand(), null);
        $enriched = $this->repository()->enrichWithFragmentSummary($rows);

        $page4 = current(array_filter($enriched, static fn(array $row): bool => (int)$row['uid'] === 4));
        self::assertSame(2, $page4['fragmentCount']);
        // Order-independent: "distinct scopes used across a page's
        // fragments" has no meaningful order of its own, unlike
        // $page4['fragments'] below (covered separately), which does.
        self::assertEqualsCanonicalizing([PromptFragmentScope::Text->value, PromptFragmentScope::All->value], $page4['scopes']);

        $page1 = current(array_filter($enriched, static fn(array $row): bool => (int)$row['uid'] === 1));
        self::assertSame(1, $page1['fragmentCount']);
        self::assertSame([PromptFragmentScope::Text->value], $page1['scopes']);
    }

    #[Test]
    public function enrichWithFragmentSummaryReportsEveryCapabilityOfAMultiScopeFragmentSeparately(): void
    {
        $rows = $this->repository()->findByDemand(new PagePromptFragmentDemand(), null);
        $enriched = $this->repository()->enrichWithFragmentSummary($rows);

        $page5 = current(array_filter($enriched, static fn(array $row): bool => (int)$row['uid'] === 5));
        self::assertSame(1, $page5['fragmentCount']);
        self::assertSame([PromptFragmentScope::Text->value, PromptFragmentScope::Vision->value], $page5['scopes']);
    }

    /**
     * Regression test: the Preview list's own "N fragment(s)" disclosure
     * (mirroring the Library module's "used on N page(s)" one) needs the
     * individual fragments themselves, not just the aggregate count/scopes
     * enrichWithFragmentSummary() already provided.
     */
    #[Test]
    public function enrichWithFragmentSummaryAlsoListsTheIndividualFragmentsPerPage(): void
    {
        $rows = $this->repository()->findByDemand(new PagePromptFragmentDemand(), null);
        $enriched = $this->repository()->enrichWithFragmentSummary($rows);

        $page1 = current(array_filter($enriched, static fn(array $row): bool => (int)$row['uid'] === 1));
        self::assertSame(
            [['uid' => $page1['fragments'][0]['uid'], 'title' => 'Fragment A', 'pid' => 0, 'scope' => PromptFragmentScope::Text->value]],
            $page1['fragments'],
        );
    }

    /**
     * Regression test: this list used to be ordered by fragment title,
     * which is a different order than PagePromptResolver::fetchFragmentsByPage()
     * actually walks when composing the real prompt (ordered by the
     * assignment's own `sorting` - the manual drag order set in the page
     * edit form's IRRE field). Page 4's fixture deliberately assigns
     * "Fragment C1" a HIGHER sorting value than "Fragment C2" (the reverse
     * of their alphabetical order), so this can only pass if the query
     * really follows assignment order, not title.
     */
    #[Test]
    public function enrichWithFragmentSummaryOrdersFragmentsByTheirAssignmentSortingNotTitle(): void
    {
        $rows = $this->repository()->findByDemand(new PagePromptFragmentDemand(), null);
        $enriched = $this->repository()->enrichWithFragmentSummary($rows);

        $page4 = current(array_filter($enriched, static fn(array $row): bool => (int)$row['uid'] === 4));
        self::assertSame(['Fragment C2', 'Fragment C1'], array_column($page4['fragments'], 'title'));
    }

    #[Test]
    public function pagesWithoutFragmentsCanExistAlongsideEnrichedResultsWithoutErrors(): void
    {
        self::assertSame([], $this->repository()->enrichWithFragmentSummary([]));
    }

    #[Test]
    public function upsertAutoDetectedFragmentCreatesANewFragmentWhenNoneExistsYet(): void
    {
        // Page 3 ("No fragments") has none seeded in setUp().
        $fragmentUid = $this->repository()->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'Be warm.', 'Q: Hi\nA: Hello!', ['text', 'vision'], AutoGeneratedFragmentSource::Cli);

        $fragmentRow = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment')
            ->select(['*'], 'tx_aim_prompt_fragment', ['uid' => $fragmentUid])
            ->fetchAssociative();
        self::assertSame(3, (int)$fragmentRow['pid']);
        self::assertSame('Be warm.', $fragmentRow['prompt']);
        self::assertSame('text,vision', $fragmentRow['scope']);

        $assignmentRow = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment')
            ->select(['*'], 'tx_aim_page_prompt_fragment', ['parent_page' => 3])
            ->fetchAssociative();
        self::assertSame(3, (int)$assignmentRow['pid']);
        self::assertSame(3, (int)$assignmentRow['parent_page']);
        self::assertSame($fragmentUid, (int)$assignmentRow['fragment']);
        self::assertSame(1, (int)$assignmentRow['auto_generated']);
        self::assertSame(1, (int)$assignmentRow['inherit_to_subpages']);
        self::assertSame(AutoGeneratedFragmentSource::Cli->value, $assignmentRow['auto_generated_source']);
    }

    /**
     * Regression test: auto_generated_source must be re-asserted on every
     * write, not just set once at creation, so it always reflects whoever
     * produced the CURRENT content, e.g. a page first calibrated via the
     * CLI command and later re-derived from an uploaded document (or the
     * other way around) must end up correctly labeled as the latter, not
     * stuck reporting its original source.
     */
    #[Test]
    public function upsertAutoDetectedFragmentUpdatesTheSourceOnASubsequentRunFromADifferentCaller(): void
    {
        $repository = $this->repository();
        $repository->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'First tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);
        $repository->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'Uploaded tone.', '', ['text'], AutoGeneratedFragmentSource::Upload);

        $assignmentRow = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment')
            ->select(['auto_generated_source'], 'tx_aim_page_prompt_fragment', ['parent_page' => 3, 'auto_generated' => 1])
            ->fetchAssociative();
        self::assertSame(AutoGeneratedFragmentSource::Upload->value, $assignmentRow['auto_generated_source']);
    }

    #[Test]
    public function upsertAutoDetectedFragmentUpdatesTheSameRecordOnASecondRun(): void
    {
        $repository = $this->repository();
        $firstUid = $repository->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'First tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);
        $secondUid = $repository->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'Refreshed tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);

        self::assertSame($firstUid, $secondUid);

        $connection = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $count = $connection->count('uid', 'tx_aim_page_prompt_fragment', ['parent_page' => 3, 'auto_generated' => 1]);
        self::assertSame(1, $count);

        $row = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment')
            ->select(['prompt'], 'tx_aim_prompt_fragment', ['uid' => $firstUid])
            ->fetchAssociative();
        self::assertSame('Refreshed tone.', $row['prompt']);
    }

    #[Test]
    public function upsertAutoDetectedFragmentNeverTouchesAnEditorAuthoredFragment(): void
    {
        // Page 1 already has a hand-authored assignment from setUp() (no
        // auto_generated flag), so upserting must ADD a second, separate
        // auto-detected assignment (and fragment) rather than overwrite the
        // existing one.
        $uid = $this->repository()->upsertAutoDetectedFragment(1, 'Tone of voice (auto-detected)', 'Auto tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);

        $connection = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $total = $connection->count('uid', 'tx_aim_page_prompt_fragment', ['parent_page' => 1]);
        self::assertSame(2, $total);

        $handAuthored = $connection->count('uid', 'tx_aim_page_prompt_fragment', ['parent_page' => 1, 'auto_generated' => 0]);
        self::assertSame(1, $handAuthored);
        self::assertNotSame(0, $uid);
    }

    /**
     * Regression test: upsertAutoDetectedFragment() used to UPDATE the
     * existing auto-detected fragment's row in place on every re-run. But
     * that fragment is a real, globally-selectable library entry, so an
     * editor could reuse it on a completely different page via the suggest
     * wizard between calibration runs. The next run would then silently
     * overwrite content that other page now also relies on. It must detach
     * into a fresh fragment and repoint its own assignment instead, leaving
     * the shared fragment (and the other page using it) untouched.
     */
    #[Test]
    public function upsertAutoDetectedFragmentDetachesIntoANewFragmentInsteadOfClobberingOneReusedElsewhere(): void
    {
        $repository = $this->repository();
        $firstUid = $repository->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'First tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);

        // Editor reuses the auto-detected fragment on a different page via
        // the suggest wizard, independently of the calibration workflow.
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 2, 'parent_page' => 2, 'fragment' => $firstUid]);

        $secondUid = $repository->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'Refreshed tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);

        self::assertNotSame($firstUid, $secondUid, 'A new fragment must be created rather than overwriting the shared one.');

        $originalFragment = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment')
            ->select(['prompt'], 'tx_aim_prompt_fragment', ['uid' => $firstUid])
            ->fetchAssociative();
        self::assertSame('First tone.', $originalFragment['prompt'], 'The fragment still used by another page must keep its original content.');

        $page3Assignment = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment')
            ->select(['fragment'], 'tx_aim_page_prompt_fragment', ['parent_page' => 3, 'auto_generated' => 1])
            ->fetchAssociative();
        self::assertSame($secondUid, (int)$page3Assignment['fragment'], "Page 3's own auto-generated assignment must now point at the new fragment.");
        self::assertSame(
            1,
            $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment')
                ->count('uid', 'tx_aim_page_prompt_fragment', ['parent_page' => 3, 'auto_generated' => 1]),
            'The existing assignment must be repointed, not duplicated into a second one.',
        );
    }

    /**
     * Regression test: if the auto-generated assignment's `fragment` FK is
     * 0 (e.g. the FK was never set on a hand-crafted/legacy row), updating
     * "fragment uid 0" used to silently match no rows at all - the command
     * would report success and a fresh uid, but nothing was actually ever
     * persisted anywhere reachable. It must instead create a new fragment
     * and repair the assignment's FK to point at it.
     */
    #[Test]
    public function upsertAutoDetectedFragmentRepairsAnAssignmentWhoseFragmentFkIsZero(): void
    {
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 3, 'parent_page' => 3, 'fragment' => 0, 'auto_generated' => 1]);

        $fragmentUid = $this->repository()->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'Repaired tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);

        self::assertNotSame(0, $fragmentUid);
        $fragmentRow = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment')
            ->select(['prompt'], 'tx_aim_prompt_fragment', ['uid' => $fragmentUid])
            ->fetchAssociative();
        self::assertSame('Repaired tone.', $fragmentRow['prompt']);

        $assignmentRow = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment')
            ->select(['fragment'], 'tx_aim_page_prompt_fragment', ['parent_page' => 3, 'auto_generated' => 1])
            ->fetchAssociative();
        self::assertSame($fragmentUid, (int)$assignmentRow['fragment'], 'The orphaned assignment must be repaired to point at the new fragment.');
        self::assertSame(
            1,
            $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment')
                ->count('uid', 'tx_aim_page_prompt_fragment', ['parent_page' => 3, 'auto_generated' => 1]),
            'The existing assignment must be repaired, not duplicated into a second one.',
        );
    }

    /**
     * Regression test: this is the realistic shape the "orphaned FK" bug
     * actually takes in production - nothing in this codebase ever resets
     * `fragment` back to 0 after a fragment is deleted (DataHandler doesn't
     * null out a plain `type=group` FK on the referencing side), so a
     * deleted fragment leaves the assignment's FK dangling at its old,
     * now-nonexistent uid, not at 0. Before fragmentStillExists() was
     * added, `$fragmentUid > 0` alone was true here, so the old fragment
     * row would have been targeted by an UPDATE that matches nothing (soft
     * delete) or, if hard-deleted, nothing at all - silently losing the
     * refreshed content either way while still reporting success.
     */
    #[Test]
    public function upsertAutoDetectedFragmentRepairsAnAssignmentWhoseFragmentWasDeleted(): void
    {
        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 3, 'title' => 'Tone of voice (auto-detected)', 'prompt' => 'Stale tone.', 'scope' => 'text', 'deleted' => 1]);
        $deletedFragmentUid = (int)$fragments->lastInsertId();

        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 3, 'parent_page' => 3, 'fragment' => $deletedFragmentUid, 'auto_generated' => 1]);

        $fragmentUid = $this->repository()->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'Repaired tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);

        self::assertNotSame($deletedFragmentUid, $fragmentUid, 'A new fragment must be created rather than targeting the deleted one.');
        $fragmentRow = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment')
            ->select(['prompt'], 'tx_aim_prompt_fragment', ['uid' => $fragmentUid])
            ->fetchAssociative();
        self::assertSame('Repaired tone.', $fragmentRow['prompt']);

        $assignmentRow = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment')
            ->select(['fragment'], 'tx_aim_page_prompt_fragment', ['parent_page' => 3, 'auto_generated' => 1])
            ->fetchAssociative();
        self::assertSame($fragmentUid, (int)$assignmentRow['fragment'], 'The assignment must be repaired to point at the new fragment.');
        self::assertSame(
            1,
            $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment')
                ->count('uid', 'tx_aim_page_prompt_fragment', ['parent_page' => 3, 'auto_generated' => 1]),
            'The existing assignment must be repaired, not duplicated into a second one.',
        );
    }

    /**
     * Regression test: fragmentStillExists() (used by the fix above) must
     * NOT treat a merely hidden fragment as gone - unlike a deleted one, an
     * editor disabling the auto-detected fragment is still a real row an
     * in-place UPDATE can safely refresh. Detaching into a new fragment
     * here would silently undo that hidden=1 (the replacement is created
     * visible) and leave the disabled original behind as an abandoned
     * duplicate, accumulating one more on every calibration run.
     */
    #[Test]
    public function upsertAutoDetectedFragmentRefreshesAHiddenFragmentInPlaceRatherThanDetaching(): void
    {
        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 3, 'title' => 'Tone of voice (auto-detected)', 'prompt' => 'Stale tone.', 'scope' => 'text', 'hidden' => 1]);
        $hiddenFragmentUid = (int)$fragments->lastInsertId();

        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 3, 'parent_page' => 3, 'fragment' => $hiddenFragmentUid, 'auto_generated' => 1]);

        $fragmentUid = $this->repository()->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'Refreshed tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);

        self::assertSame($hiddenFragmentUid, $fragmentUid, 'The hidden fragment must be refreshed in place, not replaced.');
        // A plain Connection::select()/count() applies the same default
        // HiddenRestriction as a QueryBuilder built via
        // getQueryBuilderForTable() - it would silently miss the very row
        // this test needs to inspect, so restrictions are removed here.
        $qb = $this->getConnectionPool()->getQueryBuilderForTable('tx_aim_prompt_fragment');
        $qb->getRestrictions()->removeAll();
        $fragmentRow = $qb->select('prompt', 'hidden')
            ->from('tx_aim_prompt_fragment')
            ->where($qb->expr()->eq('uid', $qb->createNamedParameter($hiddenFragmentUid, Connection::PARAM_INT)))
            ->executeQuery()
            ->fetchAssociative();
        self::assertSame('Refreshed tone.', $fragmentRow['prompt']);
        self::assertSame(1, (int)$fragmentRow['hidden'], "The editor's own hidden=1 must survive the refresh.");

        $countQb = $this->getConnectionPool()->getQueryBuilderForTable('tx_aim_prompt_fragment');
        $countQb->getRestrictions()->removeAll();
        $count = $countQb->count('uid')
            ->from('tx_aim_prompt_fragment')
            ->where($countQb->expr()->eq('title', $countQb->createNamedParameter('Tone of voice (auto-detected)')))
            ->executeQuery()
            ->fetchOne();
        self::assertSame(1, (int)$count, 'No abandoned duplicate fragment must be created.');
    }

    /**
     * Regression test: enrichLibraryWithUsage() used to fetch every usage
     * row for every fragment with no setMaxResults() at all, relying on the
     * *caller* to slice the list down afterward - meaning a widely-used
     * fragment's full, unbounded usage set was always fetched regardless
     * of how few of those rows would ever be shown. `usedOnPageCount` must
     * still reflect the TRUE total; only the `usedOnPages` list itself is
     * capped.
     */
    #[Test]
    public function enrichLibraryWithUsageCapsTheDetailedListButNotTheTrueCount(): void
    {
        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 20, 'pid' => 0, 'title' => 'Widely-used A']);
        $pages->insert('pages', ['uid' => 21, 'pid' => 0, 'title' => 'Widely-used B']);
        $pages->insert('pages', ['uid' => 22, 'pid' => 0, 'title' => 'Widely-used C']);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 0, 'title' => 'Widely-used fragment', 'prompt' => 'Tone.', 'scope' => 'all']);
        $fragmentUid = (int)$fragments->lastInsertId();

        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        foreach ([20, 21, 22] as $pageId) {
            $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => $pageId, 'parent_page' => $pageId, 'fragment' => $fragmentUid]);
        }

        $enriched = $this->repository()->enrichLibraryWithUsage(
            [['uid' => $fragmentUid, 'pid' => 0, 'title' => 'Widely-used fragment', 'prompt' => 'Tone.', 'examples' => '', 'scope' => 'all']],
            null,
            2,
        );

        self::assertSame(3, $enriched[0]['usedOnPageCount'], 'The true total must be reported regardless of the cap.');
        self::assertCount(2, $enriched[0]['usedOnPages'], 'The detailed list must be capped at the given maximum.');
    }

    /**
     * Regression test: findUsagePagesForFragment() used to select only
     * uid/pid/title/hidden/doktype/is_siteroot for each usage page, unlike
     * the Preview listing's own page rows (findByDemand()), which also
     * carry starttime/endtime/nav_hide/fe_group/module/content_from_pid -
     * all consulted by core:iconForRecord (the template's icon for each
     * usage-page row) to render its start/end-time, hide-in-menu, FE-group
     * and content-from-pid overlay badges. Missing them understated a
     * usage page's actual state here even though the underlying record and
     * icon call are otherwise identical to the Preview listing's own.
     */
    #[Test]
    public function findUsagePagesForFragmentCarriesEveryColumnCoreIconForRecordNeedsForOverlays(): void
    {
        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', [
            'uid' => 23,
            'pid' => 0,
            'title' => 'Time-restricted, menu-hidden page',
            'starttime' => 4102444800, // 2100-01-01, i.e. "not yet visible"
            'endtime' => 4102531200,
            'nav_hide' => 1,
            'fe_group' => '2',
            'module' => 'contentFromPid',
            'content_from_pid' => 99,
        ]);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 0, 'title' => 'Overlay test fragment', 'prompt' => 'Tone.', 'scope' => 'all']);
        $fragmentUid = (int)$fragments->lastInsertId();

        $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment')
            ->insert('tx_aim_page_prompt_fragment', ['pid' => 23, 'parent_page' => 23, 'fragment' => $fragmentUid]);

        $enriched = $this->repository()->enrichLibraryWithUsage(
            [['uid' => $fragmentUid, 'pid' => 0, 'title' => 'Overlay test fragment', 'prompt' => 'Tone.', 'examples' => '', 'scope' => 'all']],
            null,
            25,
        );

        $usagePage = $enriched[0]['usedOnPages'][0];
        self::assertSame(4102444800, $usagePage['starttime']);
        self::assertSame(4102531200, $usagePage['endtime']);
        self::assertTrue($usagePage['nav_hide']);
        self::assertSame('2', $usagePage['fe_group']);
        self::assertSame('contentFromPid', $usagePage['module']);
        self::assertSame(99, $usagePage['content_from_pid']);
    }

    /**
     * Regression test: countUsagePagesByFragment() used to aggregate over
     * the assignment table alone, with no join to `pages` - so an
     * assignment whose parent_page no longer exists (found by the
     * independent reviewer of this fix, not by me) still counted as a
     * "used" page, while findUsagePagesForFragment()'s own page JOIN
     * correctly excluded it from the actual list. That divergence would
     * render e.g. "used on 2 page(s)" with only 1 real page ever listed.
     */
    #[Test]
    public function enrichLibraryWithUsageDoesNotCountAnAssignmentWhosePageNoLongerExists(): void
    {
        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 25, 'pid' => 0, 'title' => 'Real page']);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 0, 'title' => 'Partially orphaned fragment', 'prompt' => 'Tone.', 'scope' => 'all']);
        $fragmentUid = (int)$fragments->lastInsertId();

        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 25, 'parent_page' => 25, 'fragment' => $fragmentUid]);
        // No page 999 exists: this assignment is an orphan (e.g. left over
        // from a page deletion that, for whatever reason, never cleaned up
        // its own assignment children).
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 999, 'parent_page' => 999, 'fragment' => $fragmentUid]);

        $enriched = $this->repository()->enrichLibraryWithUsage(
            [['uid' => $fragmentUid, 'pid' => 0, 'title' => 'Partially orphaned fragment', 'prompt' => 'Tone.', 'examples' => '', 'scope' => 'all']],
            null,
            25,
        );

        self::assertSame(1, $enriched[0]['usedOnPageCount'], 'The orphaned assignment must not inflate the count.');
        self::assertCount(1, $enriched[0]['usedOnPages']);
    }

    /**
     * Regression test: neither the page-list nor the library-list query
     * added WorkspaceRestriction (it is NOT part of
     * DefaultRestrictionContainer, unlike Deleted/Hidden/Start/EndTime),
     * so a workspace-version row for an assignment or a fragment showed up
     * as a second, spurious entry alongside its own live counterpart, even
     * when resolving in the live workspace (0).
     */
    #[Test]
    public function aWorkspaceVersionedFragmentOrAssignmentDoesNotAppearTwiceInEitherListing(): void
    {
        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 40, 'pid' => 0, 'title' => 'Workspace test page']);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 0, 'title' => 'Workspace-editable fragment', 'prompt' => 'Live tone.', 'scope' => 'all']);
        $liveFragmentUid = (int)$fragments->lastInsertId();
        $fragments->insert('tx_aim_prompt_fragment', [
            'pid' => 0,
            'title' => 'Workspace-editable fragment',
            'prompt' => 'Draft tone.',
            'scope' => 'all',
            't3ver_wsid' => 3,
            't3ver_oid' => $liveFragmentUid,
        ]);
        $workspaceVersionFragmentUid = (int)$fragments->lastInsertId();

        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 40, 'parent_page' => 40, 'fragment' => $liveFragmentUid]);
        $liveAssignmentUid = (int)$assignments->lastInsertId();
        $assignments->insert('tx_aim_page_prompt_fragment', [
            'pid' => 40,
            'parent_page' => 40,
            'fragment' => $liveFragmentUid,
            't3ver_wsid' => 3,
            't3ver_oid' => $liveAssignmentUid,
        ]);

        // setUp() already seeds pages 1-5 with their own fragments, so this
        // asserts page 40 appears exactly ONCE among the results, not that
        // it's the only result overall. Note: findByDemand()'s own
        // pre-existing distinct()/COUNT(DISTINCT pages.uid) already
        // incidentally collapses the two assignment rows onto the same
        // pages.uid=40 even without WorkspaceRestriction, so this
        // particular assertion doesn't by itself prove the restriction is
        // in effect - it's still a correct, worthwhile statement, just not
        // the one that would fail without the fix. That's the fragment-list
        // assertion below: two GENUINELY DIFFERENT tx_aim_prompt_fragment
        // rows (uid 1 live, uid 2 its own workspace-version copy) have no
        // equivalent natural collapsing, so findLibraryByDemand() returning
        // both would only be caught by WorkspaceRestriction actually being
        // applied - confirmed live: removing it made $workspaceVersionFragmentUid
        // (a genuinely separate tx_aim_prompt_fragment row, not a second
        // copy of the live one) show up in the results below. An earlier
        // version of this test asserted "the live uid appears exactly
        // once", which is true regardless of whether the fix is applied -
        // it never checks whether the SEPARATE workspace-version uid
        // is ALSO present, so it passed even with the fix removed. Assert
        // the workspace-version's own uid is absent instead.
        $repository = $this->repository();
        $pageRows = $repository->findByDemand(new PagePromptFragmentDemand(), null);
        $page40Occurrences = array_filter($pageRows, static fn(array $row): bool => (int)$row['uid'] === 40);
        self::assertCount(1, $page40Occurrences, 'Page 40 must not appear twice.');

        $fragmentRows = $repository->findLibraryByDemand(new PagePromptFragmentDemand(), null);
        $fragmentUids = array_map(static fn(array $row): int => (int)$row['uid'], $fragmentRows);
        self::assertContains($liveFragmentUid, $fragmentUids, 'The live fragment must still be listed.');
        self::assertNotContains($workspaceVersionFragmentUid, $fragmentUids, 'The workspace-version row must not appear as a separate, second fragment.');
    }

    /**
     * Regression test: the $usagePageIds filter's own subquery against
     * tx_aim_page_prompt_fragment used to have no WorkspaceRestriction,
     * unlike every other query this repository runs against that same
     * table (see getQueryBuilderForDemand()'s and getLibraryQueryBuilderForDemand()'s
     * own, identical comments on why it's needed: versioningWS => true,
     * but WorkspaceRestriction isn't part of DefaultRestrictionContainer).
     * A workspace-only assignment - one that only exists as a draft
     * version, with no live counterpart - must not make a fragment count
     * as "used in this subtree" for a request resolving in the live
     * workspace (0).
     */
    #[Test]
    public function findLibraryByDemandsUsageFilterIgnoresAWorkspaceOnlyAssignment(): void
    {
        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 300, 'pid' => 0, 'title' => 'Usage-filter subtree root']);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 301, 'title' => 'Workspace-only usage', 'prompt' => 'Tone.', 'scope' => 'all']);
        $fragmentUid = (int)$fragments->lastInsertId();

        // No live assignment at all for this fragment - only a
        // workspace-versioned one (t3ver_wsid != 0), pointing into the
        // tested subtree.
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', [
            'pid' => 300,
            'parent_page' => 300,
            'fragment' => $fragmentUid,
            't3ver_wsid' => 3,
        ]);

        $rows = $this->repository()->findLibraryByDemand(new PagePromptFragmentDemand(), null, [300]);
        $uids = array_map(static fn(array $row): int => (int)$row['uid'], $rows);

        self::assertNotContains($fragmentUid, $uids, 'A workspace-only assignment must not count as "used" for a live-workspace request.');
    }

    /**
     * Regression test: enrichWithFragmentSummary() ran its own query
     * against tx_aim_page_prompt_fragment/tx_aim_prompt_fragment without
     * WorkspaceRestriction, unlike getQueryBuilderForDemand()'s identical
     * join - so a workspace-only draft assignment (no live counterpart)
     * inflated a page's own fragmentCount/scopes/fragments disclosure for a
     * request resolving in the live workspace (0).
     */
    #[Test]
    public function enrichWithFragmentSummaryIgnoresAWorkspaceOnlyAssignment(): void
    {
        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 310, 'pid' => 0, 'title' => 'Fragment summary workspace test page']);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 0, 'title' => 'Draft-only fragment', 'prompt' => 'Tone.', 'scope' => 'all']);
        $fragmentUid = (int)$fragments->lastInsertId();

        // No live assignment at all for page 310 - only a workspace-versioned
        // one (t3ver_wsid != 0).
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', [
            'pid' => 310,
            'parent_page' => 310,
            'fragment' => $fragmentUid,
            't3ver_wsid' => 3,
        ]);

        $enriched = $this->repository()->enrichWithFragmentSummary([
            ['uid' => 310, 'pid' => 0, 'title' => 'Fragment summary workspace test page'],
        ]);

        self::assertSame(0, $enriched[0]['fragmentCount'], 'A workspace-only assignment must not count towards the live fragmentCount.');
        self::assertSame([], $enriched[0]['fragments']);
    }

    /**
     * Regression test: enrichLibraryWithUsage() (via
     * countUsagePagesByFragment()/findUsagePagesForFragment()) ran without
     * WorkspaceRestriction, so a workspace-only draft assignment made a
     * fragment appear "used" on a page it isn't actually assigned to in the
     * live workspace (0) - and, unlike the other two workspace regressions
     * above (which fold into other assertions), had no coverage at all.
     */
    #[Test]
    public function enrichLibraryWithUsageIgnoresAWorkspaceOnlyAssignment(): void
    {
        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 320, 'pid' => 0, 'title' => 'Usage workspace test page']);

        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', ['pid' => 0, 'title' => 'Workspace-only usage fragment', 'prompt' => 'Tone.', 'scope' => 'all']);
        $fragmentUid = (int)$fragments->lastInsertId();

        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', [
            'pid' => 320,
            'parent_page' => 320,
            'fragment' => $fragmentUid,
            't3ver_wsid' => 3,
        ]);

        $enriched = $this->repository()->enrichLibraryWithUsage(
            [['uid' => $fragmentUid, 'pid' => 0, 'title' => 'Workspace-only usage fragment', 'prompt' => 'Tone.', 'examples' => '', 'scope' => 'all']],
            null,
            25,
        );

        self::assertSame(0, $enriched[0]['usedOnPageCount'], 'A workspace-only assignment must not count as "used" for a live-workspace request.');
        self::assertSame([], $enriched[0]['usedOnPages']);
    }

    /**
     * Regression test: isFragmentSharedWithAnotherAssignment() (used by
     * upsertAutoDetectedFragment() to decide whether the existing
     * auto-detected fragment is safe to refresh in place, or must be
     * detached into a fresh one because another page already relies on it)
     * ran without WorkspaceRestriction. A page reusing the fragment only
     * via a workspace DRAFT assignment - not yet published, no live
     * counterpart - must not be treated as "sharing" it: the CLI upsert
     * should still refresh the fragment in place for the live workspace.
     */
    #[Test]
    public function upsertAutoDetectedFragmentRefreshesInPlaceWhenOnlyAWorkspaceDraftReusesIt(): void
    {
        $repository = $this->repository();
        $firstUid = $repository->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'First tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);

        // Reused on a different page, but only as a workspace draft - not
        // (yet) a live assignment.
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 2, 'parent_page' => 2, 'fragment' => $firstUid, 't3ver_wsid' => 3]);

        $secondUid = $repository->upsertAutoDetectedFragment(3, 'Tone of voice (auto-detected)', 'Refreshed tone.', '', ['text'], AutoGeneratedFragmentSource::Cli);

        self::assertSame($firstUid, $secondUid, 'A workspace-only draft reuse must not trigger a detach for the live workspace.');
        $refreshedFragment = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment')
            ->select(['prompt'], 'tx_aim_prompt_fragment', ['uid' => $firstUid])
            ->fetchAssociative();
        self::assertSame('Refreshed tone.', $refreshedFragment['prompt']);
    }
}
