<?php

declare(strict_types=1);

/*
 * This file is part of TYPO3 CMS-based extension "aim" by b13.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 */

namespace B13\Aim\Tests\Functional\Service;

use B13\Aim\Domain\Model\FragmentAssignmentCounts;
use B13\Aim\Domain\Model\PageFragmentAssignmentInfo;
use B13\Aim\Domain\Model\ToneOfVoiceInfo;
use B13\Aim\Prompt\AutoGeneratedFragmentSource;
use B13\Aim\Prompt\PromptFragmentScope;
use B13\Aim\Service\PromptManagementApi;
use PHPUnit\Framework\Attributes\Test;
use TYPO3\CMS\Core\Database\Connection;
use TYPO3\CMS\Core\Localization\LanguageServiceFactory;
use TYPO3\TestingFramework\Core\Functional\FunctionalTestCase;

/**
 * Covers PromptManagementApi as an external consumer (e.g. EXT:t3ppy's
 * Brain module) would use it: through the public methods only, never by
 * reaching into tx_aim_page_prompt_fragment/tx_aim_prompt_fragment
 * directly, which is exactly the coupling this class exists to replace.
 */
final class PromptManagementApiTest extends FunctionalTestCase
{
    protected array $testExtensionsToLoad = [
        'b13/aim',
    ];

    protected function setUp(): void
    {
        parent::setUp();

        $pages = $this->getConnectionPool()->getConnectionForTable('pages');
        $pages->insert('pages', ['uid' => 1, 'pid' => 0, 'title' => 'Root page']);
        $pages->insert('pages', ['uid' => 2, 'pid' => 0, 'title' => 'No fragments here']);

        $this->getConnectionPool()->getConnectionForTable('be_users')
            ->insert('be_users', ['uid' => 1, 'username' => 'admin', 'admin' => 1]);
        $backendUser = $this->setUpBackendUser(1);
        $GLOBALS['LANG'] = $this->get(LanguageServiceFactory::class)->createFromUserPreferences($backendUser);
    }

    private function api(): PromptManagementApi
    {
        return $this->get(PromptManagementApi::class);
    }

    #[Test]
    public function findFragmentsForPageReturnsResolvedScopeLabelsAndAnEditUrl(): void
    {
        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $fragments->insert('tx_aim_prompt_fragment', [
            'pid' => 0,
            'title' => 'House style',
            'prompt' => 'Be warm.',
            'scope' => PromptFragmentScope::Text->value . ',' . PromptFragmentScope::Vision->value,
        ]);
        $fragmentUid = (int)$fragments->lastInsertId();
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');
        $assignments->insert('tx_aim_page_prompt_fragment', [
            'pid' => 1,
            'parent_page' => 1,
            'fragment' => $fragmentUid,
            'inherit_to_subpages' => 1,
        ]);
        $assignmentUid = (int)$assignments->lastInsertId();

        $result = $this->api()->findFragmentsForPage(1, 'https://example.org/return');

        self::assertCount(1, $result);
        self::assertInstanceOf(PageFragmentAssignmentInfo::class, $result[0]);
        self::assertSame($assignmentUid, $result[0]->assignmentUid);
        self::assertSame('House style', $result[0]->title);
        self::assertSame(['Text Generation', 'Vision'], $result[0]->scopeLabels);
        self::assertTrue($result[0]->inheritToSubpages);
        self::assertStringContainsString('edit%5Btx_aim_page_prompt_fragment%5D%5B' . $assignmentUid . '%5D=edit', $result[0]->editUrl);
        self::assertStringContainsString('returnUrl=https://example.org/return', $result[0]->editUrl);
    }

    #[Test]
    public function findFragmentsForPageReturnsAnEmptyListForAPageWithNone(): void
    {
        self::assertSame([], $this->api()->findFragmentsForPage(2, 'https://example.org/return'));
    }

    #[Test]
    public function findToneOfVoiceReturnsNullWhenNoneHasBeenAutoDetectedYet(): void
    {
        self::assertNull($this->api()->findToneOfVoice(1, 'https://example.org/return'));
    }

    #[Test]
    public function findToneOfVoiceFlagsACliProducedFragmentAsCliCalibrated(): void
    {
        $this->api()->saveAutoDetectedFragment(1, 'Voice (auto-calibrated)', 'Warm and direct.', 'Example.', [PromptFragmentScope::All->value], AutoGeneratedFragmentSource::Cli);

        $result = $this->api()->findToneOfVoice(1, 'https://example.org/return');

        self::assertInstanceOf(ToneOfVoiceInfo::class, $result);
        self::assertTrue($result->isCliCalibrated);
        self::assertSame('Warm and direct.', $result->tone);
        self::assertSame('Example.', $result->examples);
        self::assertStringContainsString('edit%5Btx_aim_prompt_fragment%5D%5B' . $result->fragmentUid . '%5D=edit', $result->editUrl);
    }

    #[Test]
    public function findToneOfVoiceDoesNotFlagAnUploadedFragmentAsCliCalibrated(): void
    {
        $this->api()->saveAutoDetectedFragment(1, 'Voice (from uploaded document)', 'Second person, no jargon.', '', [PromptFragmentScope::All->value], AutoGeneratedFragmentSource::Upload);

        $result = $this->api()->findToneOfVoice(1, 'https://example.org/return');

        self::assertFalse($result->isCliCalibrated);
    }

    /**
     * Regression coverage for the exact bug this class exists to prevent:
     * isCliCalibrated must survive a title an editor renamed after the
     * fact, since it's no longer derived from the title at all.
     */
    #[Test]
    public function findToneOfVoiceIgnoresTheTitleWhenDecidingIsCliCalibrated(): void
    {
        $this->api()->saveAutoDetectedFragment(1, 'Voice (auto-calibrated)', 'Warm and direct.', '', [PromptFragmentScope::All->value], AutoGeneratedFragmentSource::Cli);
        $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment')
            ->update('tx_aim_prompt_fragment', ['title' => 'Our house tone'], ['pid' => 1]);

        self::assertTrue($this->api()->findToneOfVoice(1, 'https://example.org/return')->isCliCalibrated);
    }

    #[Test]
    public function countAllFragmentAssignmentsCountsAcrossEveryPageNotJustOne(): void
    {
        $fragments = $this->getConnectionPool()->getConnectionForTable('tx_aim_prompt_fragment');
        $assignments = $this->getConnectionPool()->getConnectionForTable('tx_aim_page_prompt_fragment');

        $fragmentUid = $this->insertFragment($fragments, 'Fragment A');
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 1, 'parent_page' => 1, 'fragment' => $fragmentUid, 'inherit_to_subpages' => 1]);

        $secondFragmentUid = $this->insertFragment($fragments, 'Fragment B');
        $assignments->insert('tx_aim_page_prompt_fragment', ['pid' => 2, 'parent_page' => 2, 'fragment' => $secondFragmentUid, 'inherit_to_subpages' => 0]);

        $counts = $this->api()->countAllFragmentAssignments();

        self::assertInstanceOf(FragmentAssignmentCounts::class, $counts);
        self::assertSame(2, $counts->total);
        self::assertSame(1, $counts->inherited);
    }

    #[Test]
    public function buildPromptManagementUrlPointsAtTheCorrectRoute(): void
    {
        self::assertStringContainsString('/prompt-management', $this->api()->buildPromptManagementUrl(['view' => 'pages']));
    }

    private function insertFragment(Connection $connection, string $title): int
    {
        $connection->insert('tx_aim_prompt_fragment', [
            'pid' => 0,
            'title' => $title,
            'prompt' => 'Some tone.',
            'scope' => PromptFragmentScope::Text->value,
        ]);
        return (int)$connection->lastInsertId();
    }
}
