<?php

declare(strict_types=1);

/*
 * This file is part of TYPO3 CMS-based extension "aim" by b13.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 */

namespace B13\Aim\Response;

/**
 * A single image generated by an ImageGenerationCapableInterface provider.
 *
 * Represents exactly one of two shapes a provider can return: inline base64 data,
 * or a temporary URL (e.g. providers that upload the result and hand back a link
 * instead of the bytes). Use fromBase64()/fromUrl() to construct; check isUrl()
 * to know which one you have before reading data/mimeType or url.
 */
final class GeneratedImage
{
    private function __construct(
        public readonly string $data,
        public readonly string $mimeType,
        public readonly string $url,
    ) {}

    public static function fromBase64(string $data, string $mimeType): self
    {
        return new self($data, $mimeType, '');
    }

    public static function fromUrl(string $url): self
    {
        return new self('', '', $url);
    }

    public function isUrl(): bool
    {
        return $this->url !== '';
    }

    /**
     * Data URI for inline display/storage. Only meaningful when isUrl() is false.
     */
    public function toDataUri(): string
    {
        return 'data:' . $this->mimeType . ';base64,' . $this->data;
    }
}
