<?php

declare(strict_types=1);

/*
 * This file is part of TYPO3 CMS-based extension "aim" by b13.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 */

namespace B13\Aim\Domain\Repository;

use B13\Aim\Prompt\AutoGeneratedFragmentSource;
use B13\Aim\Prompt\PromptFragmentScope;
use TYPO3\CMS\Core\Database\Connection;
use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Database\Query\QueryBuilder;
use TYPO3\CMS\Core\Database\Query\Restriction\DeletedRestriction;
use TYPO3\CMS\Core\Database\Query\Restriction\EndTimeRestriction;
use TYPO3\CMS\Core\Database\Query\Restriction\HiddenRestriction;
use TYPO3\CMS\Core\Database\Query\Restriction\StartTimeRestriction;
use TYPO3\CMS\Core\Database\Query\Restriction\WorkspaceRestriction;
use TYPO3\CMS\Core\Utility\GeneralUtility;

/**
 * Finds `pages` records that have at least one `tx_aim_prompt_fragment`
 * assigned via a `tx_aim_page_prompt_fragment` record.
 */
class PagePromptFragmentRepository
{
    private const PAGES_TABLE = 'pages';
    private const ASSIGNMENT_TABLE = 'tx_aim_page_prompt_fragment';
    private const FRAGMENT_TABLE = 'tx_aim_prompt_fragment';

    public function __construct(
        private readonly ConnectionPool $connectionPool,
    ) {}

    /**
     * @param list<int>|null $accessiblePageIds null = unrestricted (admin); [] must short-circuit to no results
     * @return list<array<string, mixed>>
     */
    public function findByDemand(PagePromptFragmentDemand $demand, ?array $accessiblePageIds): array
    {
        if ($accessiblePageIds === []) {
            return [];
        }
        $qb = $this->getQueryBuilderForDemand($demand, $accessiblePageIds);
        $qb->distinct()
            ->select(
                'pages.uid',
                'pages.pid',
                'pages.title',
                'pages.tx_aim_disable_inherited_fragments',
                'pages.doktype',
                'pages.is_siteroot',
                'pages.nav_hide',
                'pages.module',
                'pages.content_from_pid',
                'pages.hidden',
                'pages.starttime',
                'pages.endtime',
                'pages.fe_group',
                'pages.perms_userid',
                'pages.perms_groupid',
                'pages.perms_user',
                'pages.perms_group',
                'pages.perms_everybody',
            )
            ->orderBy('pages.' . $demand->getOrderField(), $demand->getOrderDirection())
            ->addOrderBy('pages.uid', 'asc')
            ->setMaxResults($demand->getLimit())
            ->setFirstResult($demand->getOffset());

        return $qb->executeQuery()->fetchAllAssociative();
    }

    /**
     * @param list<int>|null $accessiblePageIds
     */
    public function countByDemand(PagePromptFragmentDemand $demand, ?array $accessiblePageIds): int
    {
        if ($accessiblePageIds === []) {
            return 0;
        }
        // The join underneath (same as findByDemand()) produces one row per
        // matching fragment, so a plain COUNT(*) would count fragments, not
        // pages. A page with 3 matching fragments would count as 3.
        // COUNT(DISTINCT pages.uid) is the correct "how many distinct pages
        // match" query.
        $qb = $this->getQueryBuilderForDemand($demand, $accessiblePageIds);
        // count() quotes its entire argument as a single identifier, so it
        // can't express "DISTINCT column", addSelectLiteral() with a raw
        // COUNT(DISTINCT ...) expression is this codebase's own established
        // way around that (see RequestLogRepository's aggregate queries).
        $qb->addSelectLiteral('COUNT(DISTINCT ' . $qb->quoteIdentifier('pages.uid') . ')');
        return (int)$qb->executeQuery()->fetchOne();
    }

    /**
     * Adds `fragmentCount`, `scopes` (list<string>, distinct) and `fragments`
     * (list<array{uid: int, title: string, scope: string}>, the individual
     * fragments themselves, for the Preview list's own "N fragment(s)"
     * disclosure, mirroring the Library module's "used on N page(s)" one) to
     * each given page row, from a single follow-up query scoped to just
     * those page ids, not the whole matching set, so this never grows with
     * total fragment/page count, only with the current result page size.
     *
     * @param list<array<string, mixed>> $pageRows
     * @return list<array<string, mixed>>
     */
    public function enrichWithFragmentSummary(array $pageRows): array
    {
        if ($pageRows === []) {
            return [];
        }
        $pageIds = array_map(static fn(array $row): int => (int)$row['uid'], $pageRows);

        $qb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        $qb->getRestrictions()->add(GeneralUtility::makeInstance(WorkspaceRestriction::class, 0));
        $rows = $qb->select(
            self::ASSIGNMENT_TABLE . '.parent_page',
            self::FRAGMENT_TABLE . '.uid AS fragment_uid',
            self::FRAGMENT_TABLE . '.title AS fragment_title',
            self::FRAGMENT_TABLE . '.pid AS fragment_pid',
            self::FRAGMENT_TABLE . '.scope',
        )
            ->from(self::ASSIGNMENT_TABLE)
            ->innerJoin(
                self::ASSIGNMENT_TABLE,
                self::FRAGMENT_TABLE,
                self::FRAGMENT_TABLE,
                $qb->expr()->eq(self::FRAGMENT_TABLE . '.uid', $qb->quoteIdentifier(self::ASSIGNMENT_TABLE . '.fragment')),
            )
            ->where(
                $qb->expr()->in(self::ASSIGNMENT_TABLE . '.parent_page', $qb->createNamedParameter($pageIds, Connection::PARAM_INT_ARRAY)),
            )
            ->orderBy(self::ASSIGNMENT_TABLE . '.sorting')
            ->addOrderBy(self::ASSIGNMENT_TABLE . '.uid')
            ->executeQuery()
            ->fetchAllAssociative();

        $countByPage = [];
        $scopesByPage = [];
        $fragmentsByPage = [];
        foreach ($rows as $row) {
            $pageId = (int)$row['parent_page'];
            $countByPage[$pageId] = ($countByPage[$pageId] ?? 0) + 1;
            foreach (PromptFragmentScope::parseList((string)$row['scope']) as $scopeValue) {
                $scopesByPage[$pageId][$scopeValue] = true;
            }
            $fragmentsByPage[$pageId][] = [
                'uid' => (int)$row['fragment_uid'],
                'title' => (string)$row['fragment_title'],
                'pid' => (int)$row['fragment_pid'],
                'scope' => (string)$row['scope'],
            ];
        }

        return array_map(static function (array $pageRow) use ($countByPage, $scopesByPage, $fragmentsByPage): array {
            $pageId = (int)$pageRow['uid'];
            $pageRow['fragmentCount'] = $countByPage[$pageId] ?? 0;
            $pageRow['scopes'] = array_keys($scopesByPage[$pageId] ?? []);
            $pageRow['fragments'] = $fragmentsByPage[$pageId] ?? [];
            return $pageRow;
        }, $pageRows);
    }

    /**
     * Every assignment made directly on one specific page
     *
     * @return list<array{uid: int, inherit_to_subpages: int, title: string, scope: string}>
     */
    public function findAssignmentsForPage(int $pageId): array
    {
        $qb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        return $qb->select(
            self::ASSIGNMENT_TABLE . '.uid',
            self::ASSIGNMENT_TABLE . '.inherit_to_subpages',
            self::FRAGMENT_TABLE . '.title',
            self::FRAGMENT_TABLE . '.scope',
        )
            ->from(self::ASSIGNMENT_TABLE)
            ->innerJoin(
                self::ASSIGNMENT_TABLE,
                self::FRAGMENT_TABLE,
                self::FRAGMENT_TABLE,
                $qb->expr()->eq(self::FRAGMENT_TABLE . '.uid', $qb->quoteIdentifier(self::ASSIGNMENT_TABLE . '.fragment')),
            )
            ->where($qb->expr()->eq(self::ASSIGNMENT_TABLE . '.parent_page', $qb->createNamedParameter($pageId, Connection::PARAM_INT)))
            ->orderBy(self::ASSIGNMENT_TABLE . '.sorting')
            ->executeQuery()
            ->fetchAllAssociative();
    }

    /**
     * The single auto-detected fragment (auto_generated=1)
     * for a root page. Returns null when none exists yet.
     *
     * @return array{uid: int, title: string, prompt: string, examples: string, auto_generated_source: string}|null
     */
    public function findAutoDetectedFragmentForRootPage(int $rootPageId): ?array
    {
        $qb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        $row = $qb->select(
            self::FRAGMENT_TABLE . '.uid',
            self::FRAGMENT_TABLE . '.title',
            self::FRAGMENT_TABLE . '.prompt',
            self::FRAGMENT_TABLE . '.examples',
            self::ASSIGNMENT_TABLE . '.auto_generated_source',
        )
            ->from(self::ASSIGNMENT_TABLE)
            ->innerJoin(
                self::ASSIGNMENT_TABLE,
                self::FRAGMENT_TABLE,
                self::FRAGMENT_TABLE,
                $qb->expr()->eq(self::FRAGMENT_TABLE . '.uid', $qb->quoteIdentifier(self::ASSIGNMENT_TABLE . '.fragment')),
            )
            ->where(
                $qb->expr()->eq(self::ASSIGNMENT_TABLE . '.parent_page', $qb->createNamedParameter($rootPageId, Connection::PARAM_INT)),
                $qb->expr()->eq(self::ASSIGNMENT_TABLE . '.auto_generated', $qb->createNamedParameter(1, Connection::PARAM_INT)),
            )
            ->executeQuery()
            ->fetchAssociative();

        return $row === false ? null : $row;
    }

    /**
     * Install-wide assignment counts, used when no single page is selected.
     * Counts assignments (page usages), not library fragments.
     *
     * @return array{total: int, inherited: int}
     */
    public function countAllAssignments(): array
    {
        $totalQb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        $total = (int)$totalQb->count('uid')->from(self::ASSIGNMENT_TABLE)
            ->executeQuery()->fetchOne();

        $inheritedQb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        $inherited = (int)$inheritedQb->count('uid')->from(self::ASSIGNMENT_TABLE)
            ->where($inheritedQb->expr()->eq('inherit_to_subpages', $inheritedQb->createNamedParameter(1, Connection::PARAM_INT)))
            ->executeQuery()->fetchOne();

        return ['total' => $total, 'inherited' => $inherited];
    }

    /**
     * Creates or updates the single auto-detected fragment for a page
     * (marked via auto_generated=1 on the ASSIGNMENT, since that's what's
     * keyed by page now), whether the caller is aim's own aim:calibrateVoice
     * command or a consumer's own equivalent (see AutoGeneratedFragmentSource).
     * Upserts rather than appending a new assignment every run, so
     * re-running the same caller refreshes that same fragment's content
     * instead of piling up duplicates. An editor's own hand-authored
     * assignments (auto_generated=0, the default for anything created
     * through the normal edit form) are never matched or touched by this,
     * since the lookup is scoped to auto_generated=1.
     *
     * The library fragment is stored at pid=$pageId (the site's root page
     * itself): a page's own rootline always includes itself, so this
     * placement always satisfies the itemsProcFunc's "within this site
     * tree" selectability rule without any special-casing.
     *
     * $source is stored on the assignment alongside auto_generated. Re-asserted
     * on every write, including an in-place refresh of an already-existing row,
     * so it always reflects whichever caller produced the CURRENT content,
     * not just whoever created the row first.
     *
     * Bypasses DataHandler deliberately.
     */
    public function upsertAutoDetectedFragment(int $pageId, string $title, string $prompt, string $examples, array $scope, AutoGeneratedFragmentSource $source): int
    {
        $assignmentQb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        $existingAssignment = $assignmentQb
            ->select('uid', 'fragment')
            ->from(self::ASSIGNMENT_TABLE)
            ->where(
                $assignmentQb->expr()->eq('parent_page', $assignmentQb->createNamedParameter($pageId, Connection::PARAM_INT)),
                $assignmentQb->expr()->eq('auto_generated', $assignmentQb->createNamedParameter(1, Connection::PARAM_INT)),
            )
            ->executeQuery()
            ->fetchAssociative();

        $fragmentValues = [
            'title' => $title,
            'prompt' => $prompt,
            'examples' => $examples,
            'scope' => implode(',', $scope),
            'tstamp' => time(),
        ];

        $fragmentConnection = $this->connectionPool->getConnectionForTable(self::FRAGMENT_TABLE);
        $assignmentConnection = $this->connectionPool->getConnectionForTable(self::ASSIGNMENT_TABLE);

        if ($existingAssignment !== false) {
            $fragmentUid = (int)$existingAssignment['fragment'];
            $assignmentUid = (int)$existingAssignment['uid'];
            // fragmentUid === 0 (FK never set) or the fragment no longer
            // existing (deleted independently, e.g. by an editor, leaving a
            // dangling non-zero FK - the realistic orphan, since nothing in
            // this codebase ever resets the FK back to 0) both mean an
            // in-place UPDATE would silently touch nothing usable, while
            // still reporting success. isFragmentSharedWithAnotherAssignment()
            // covers the other silent-corruption case: this fragment is a
            // real, globally-selectable library row, so an editor could
            // have reused it on a different page via the suggest wizard
            // since the last run. Updating it in place here would then
            // overwrite content that other page now also relies on, with
            // no warning. In any of these cases, detach into a fresh
            // fragment instead of touching the existing row, and repoint
            // this one assignment at it.
            if ($fragmentUid > 0 && $this->fragmentStillExists($fragmentUid) && !$this->isFragmentSharedWithAnotherAssignment($fragmentUid, $assignmentUid)) {
                $fragmentConnection->update(self::FRAGMENT_TABLE, $fragmentValues, ['uid' => $fragmentUid]);
                $assignmentConnection->update(self::ASSIGNMENT_TABLE, ['auto_generated_source' => $source->value, 'tstamp' => time()], ['uid' => $assignmentUid]);
                return $fragmentUid;
            }

            $fragmentConnection->insert(self::FRAGMENT_TABLE, [
                ...$fragmentValues,
                'pid' => $pageId,
                'crdate' => time(),
            ]);
            $newFragmentUid = (int)$fragmentConnection->lastInsertId(self::FRAGMENT_TABLE);
            $assignmentConnection->update(
                self::ASSIGNMENT_TABLE,
                ['fragment' => $newFragmentUid, 'auto_generated_source' => $source->value, 'tstamp' => time()],
                ['uid' => $assignmentUid],
            );
            return $newFragmentUid;
        }

        $fragmentConnection->insert(self::FRAGMENT_TABLE, [
            ...$fragmentValues,
            'pid' => $pageId,
            'crdate' => time(),
        ]);
        $fragmentUid = (int)$fragmentConnection->lastInsertId(self::FRAGMENT_TABLE);

        $assignmentConnection->insert(self::ASSIGNMENT_TABLE, [
            'pid' => $pageId,
            'parent_page' => $pageId,
            'fragment' => $fragmentUid,
            'auto_generated' => 1,
            'auto_generated_source' => $source->value,
            'inherit_to_subpages' => 1,
            'crdate' => time(),
            'tstamp' => time(),
        ]);

        return $fragmentUid;
    }

    /**
     * Whether $fragmentUid is referenced by any assignment OTHER than
     * $excludeAssignmentUid, e.g. whether it has been reused on another
     * page (or a second time on the same page) since it was first created.
     */
    private function isFragmentSharedWithAnotherAssignment(int $fragmentUid, int $excludeAssignmentUid): bool
    {
        $qb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        // See getQueryBuilderForDemand()'s identical comment: without this,
        // a workspace-only assignment reusing $fragmentUid would count as
        // "shared", even though it has no live counterpart yet.
        $qb->getRestrictions()->add(GeneralUtility::makeInstance(WorkspaceRestriction::class, 0));
        $count = $qb->count('uid')
            ->from(self::ASSIGNMENT_TABLE)
            ->where(
                $qb->expr()->eq('fragment', $qb->createNamedParameter($fragmentUid, Connection::PARAM_INT)),
                $qb->expr()->neq('uid', $qb->createNamedParameter($excludeAssignmentUid, Connection::PARAM_INT)),
            )
            ->executeQuery()
            ->fetchOne();

        return (int)$count > 0;
    }

    /**
     * Whether $fragmentUid still refers to a real, non-deleted row - the
     * default DeletedRestriction (part of getQueryBuilderForTable()'s
     * DefaultRestrictionContainer) excludes a soft-deleted one exactly as
     * it would a hard-deleted/never-existing one. HiddenRestriction is
     * explicitly removed, matching this class's own established convention
     * (see countUsagePagesByFragment()/findUsagePagesForFragment()): a
     * fragment an editor merely disabled is still a real row an
     * in-place UPDATE can safely refresh, not an orphan needing a detach -
     * treating it as gone would silently undo the editor's own hidden=1
     * and leave it as an abandoned duplicate in the library.
     */
    private function fragmentStillExists(int $fragmentUid): bool
    {
        $qb = $this->connectionPool->getQueryBuilderForTable(self::FRAGMENT_TABLE);
        $qb->getRestrictions()->removeByType(HiddenRestriction::class);
        $count = $qb->count('uid')
            ->from(self::FRAGMENT_TABLE)
            ->where($qb->expr()->eq('uid', $qb->createNamedParameter($fragmentUid, Connection::PARAM_INT)))
            ->executeQuery()
            ->fetchOne();

        return (int)$count > 0;
    }

    /**
     * @param list<int>|null $accessiblePageIds
     */
    private function getQueryBuilderForDemand(PagePromptFragmentDemand $demand, ?array $accessiblePageIds): QueryBuilder
    {
        $qb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        $qb->getRestrictions()->add(GeneralUtility::makeInstance(WorkspaceRestriction::class, 0));
        $qb->from(self::ASSIGNMENT_TABLE)
            ->innerJoin(
                self::ASSIGNMENT_TABLE,
                self::PAGES_TABLE,
                self::PAGES_TABLE,
                $qb->expr()->eq(self::PAGES_TABLE . '.uid', $qb->quoteIdentifier(self::ASSIGNMENT_TABLE . '.parent_page')),
            )
            ->innerJoin(
                self::ASSIGNMENT_TABLE,
                self::FRAGMENT_TABLE,
                self::FRAGMENT_TABLE,
                $qb->expr()->eq(self::FRAGMENT_TABLE . '.uid', $qb->quoteIdentifier(self::ASSIGNMENT_TABLE . '.fragment')),
            );

        if ($demand->hasScope() && $demand->getScope() !== PromptFragmentScope::All) {
            $qb->andWhere($qb->expr()->or(
                $qb->expr()->inSet(self::FRAGMENT_TABLE . '.scope', $qb->quote(PromptFragmentScope::All->value)),
                $qb->expr()->inSet(self::FRAGMENT_TABLE . '.scope', $qb->quote($demand->getScope()->value)),
            ));
        }

        if ($demand->hasSearch()) {
            $escaped = '%' . $qb->escapeLikeWildcards($demand->getSearch()) . '%';
            $qb->andWhere($qb->expr()->or(
                $qb->expr()->like(self::FRAGMENT_TABLE . '.prompt', $qb->createNamedParameter($escaped)),
                $qb->expr()->like(self::FRAGMENT_TABLE . '.examples', $qb->createNamedParameter($escaped)),
                $qb->expr()->like(self::FRAGMENT_TABLE . '.title', $qb->createNamedParameter($escaped)),
            ));
        }

        if ($accessiblePageIds !== null) {
            $qb->andWhere($qb->expr()->in(
                'pages.uid',
                $qb->createNamedParameter($accessiblePageIds, Connection::PARAM_INT_ARRAY),
            ));
        }

        return $qb;
    }

    /**
     * Library listing: every reusable fragment (not the pages that use
     * them), for browsing/reuse rather than per-page management. Restricted
     * to fragments at pid=0 (global) or within the current user's
     * accessible pages for non-admins. A strict subset of what the
     * fragment picker's own itemsProcFunc would allow (that additionally
     * allows any page within an accessible site's tree, not just pages
     * literally in the accessible-id list), so this can only under-show,
     * never leak a fragment a restricted user couldn't otherwise reach.
     *
     * @param list<int>|null $accessiblePageIds
     * @param list<int>|null $usagePageIds
     * @return list<array<string, mixed>>
     */
    public function findLibraryByDemand(PagePromptFragmentDemand $demand, ?array $accessiblePageIds, ?array $usagePageIds = null): array
    {
        // Unlike findByDemand()/countByDemand() above, an empty
        // $accessiblePageIds must NOT short-circuit here: pid=0 (global)
        // fragments stay visible regardless of how many pages the user can
        // reach (see getLibraryQueryBuilderForDemand()'s own "pid = 0 OR pid
        // IN (...)". The same rule PromptFragmentSuggestReceiver enforces
        // for the suggest wizard). Short-circuiting to [] here would hide
        // those global fragments from a restricted user with zero
        // accessible pages, when the query itself would still show them.
        $qb = $this->getLibraryQueryBuilderForDemand($demand, $accessiblePageIds, $usagePageIds);
        $qb->select('uid', 'pid', 'title', 'prompt', 'examples', 'scope', 'hidden')
            ->orderBy($demand->getOrderField(), $demand->getOrderDirection())
            ->addOrderBy('uid', 'asc')
            ->setMaxResults($demand->getLimit())
            ->setFirstResult($demand->getOffset());

        return $qb->executeQuery()->fetchAllAssociative();
    }

    /**
     * @param list<int>|null $accessiblePageIds
     * @param list<int>|null $usagePageIds
     */
    public function countLibraryByDemand(PagePromptFragmentDemand $demand, ?array $accessiblePageIds, ?array $usagePageIds = null): int
    {
        $qb = $this->getLibraryQueryBuilderForDemand($demand, $accessiblePageIds, $usagePageIds);
        $qb->count('uid');
        return (int)$qb->executeQuery()->fetchOne();
    }

    /**
     * Adds `usedOnPageCount` and `usedOnPages` (list<array{uid: int, title:
     * string, pid: int, hidden: bool}>, sorted by title): which pages,
     * within what the current user may see, have an assignment pointing at
     * this fragment. Restricted to $accessiblePageIds the same way the
     * Pages listing itself is, so this never reveals whether an
     * inaccessible page also uses the fragment: a restricted user just
     * sees a possibly-shorter list, never an error or a leaked page
     * reference.
     *
     * Deliberately bypasses the `pages` table's own hidden/start/end-time
     * restrictions (its deleted one, the only other one TYPO3 applies by
     * default here, still stays in effect).
     *
     * One page can (rarely) have more than one assignment pointing at the
     * same fragment (e.g. two assignments with different scopes); rows are
     * deduplicated by page uid so such a page is listed once, not twice.
     *
     * `usedOnPageCount` always reflects the TRUE total (a cheap, GROUP BY
     * aggregate joined to `pages` so an orphaned assignment - one whose
     * parent_page no longer exists - can't inflate it, unaffected by
     * $maxPagesShown); `usedOnPages` is capped to $maxPagesShown per
     * fragment. Deliberately one detail query per fragment (bounded by
     * however many fragments are on this one demanded page, typically the
     * same handful as $demand->getLimit()) rather than a single unbounded
     * query for the whole page-of-fragments: a fragment inherited across a
     * large site could otherwise return thousands of usage rows just to
     * render $maxPagesShown of them, with no setMaxResults() to stop it.
     *
     * @param list<array<string, mixed>> $fragmentRows
     * @param list<int>|null $accessiblePageIds
     * @return list<array<string, mixed>>
     */
    public function enrichLibraryWithUsage(array $fragmentRows, ?array $accessiblePageIds, int $maxPagesShown): array
    {
        if ($fragmentRows === []) {
            return [];
        }
        if ($accessiblePageIds === []) {
            return array_map(static function (array $row): array {
                $row['usedOnPageCount'] = 0;
                $row['usedOnPages'] = [];
                return $row;
            }, $fragmentRows);
        }

        $fragmentUids = array_map(static fn(array $row): int => (int)$row['uid'], $fragmentRows);
        $countsByFragment = $this->countUsagePagesByFragment($fragmentUids, $accessiblePageIds);

        return array_map(function (array $row) use ($accessiblePageIds, $maxPagesShown, $countsByFragment): array {
            $fragmentUid = (int)$row['uid'];
            $row['usedOnPageCount'] = $countsByFragment[$fragmentUid] ?? 0;
            $row['usedOnPages'] = $row['usedOnPageCount'] > 0
                ? $this->findUsagePagesForFragment($fragmentUid, $accessiblePageIds, $maxPagesShown)
                : [];
            return $row;
        }, $fragmentRows);
    }

    /**
     * @param list<int> $fragmentUids
     * @param list<int>|null $accessiblePageIds
     * @return array<int, int> fragment uid => distinct usage page count
     */
    private function countUsagePagesByFragment(array $fragmentUids, ?array $accessiblePageIds): array
    {
        $qb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        $qb->getRestrictions()
            ->removeByType(HiddenRestriction::class)
            ->removeByType(StartTimeRestriction::class)
            ->removeByType(EndTimeRestriction::class)
            ->add(GeneralUtility::makeInstance(WorkspaceRestriction::class, 0));
        $qb->selectLiteral(
            $qb->quoteIdentifier(self::ASSIGNMENT_TABLE . '.fragment') . ' AS fragment',
            'COUNT(DISTINCT ' . $qb->quoteIdentifier(self::PAGES_TABLE . '.uid') . ') AS page_count',
        )
            ->from(self::ASSIGNMENT_TABLE)
            ->innerJoin(
                self::ASSIGNMENT_TABLE,
                self::PAGES_TABLE,
                self::PAGES_TABLE,
                $qb->expr()->eq(self::PAGES_TABLE . '.uid', $qb->quoteIdentifier(self::ASSIGNMENT_TABLE . '.parent_page')),
            )
            ->where($qb->expr()->in(self::ASSIGNMENT_TABLE . '.fragment', $qb->createNamedParameter($fragmentUids, Connection::PARAM_INT_ARRAY)))
            ->groupBy(self::ASSIGNMENT_TABLE . '.fragment');

        if ($accessiblePageIds !== null) {
            $qb->andWhere($qb->expr()->in(
                self::ASSIGNMENT_TABLE . '.parent_page',
                $qb->createNamedParameter($accessiblePageIds, Connection::PARAM_INT_ARRAY),
            ));
        }

        $counts = [];
        foreach ($qb->executeQuery()->fetchAllAssociative() as $row) {
            $counts[(int)$row['fragment']] = (int)$row['page_count'];
        }
        return $counts;
    }

    /**
     * @param list<int>|null $accessiblePageIds
     * @return list<array{uid: int, pid: int, title: string, hidden: bool, doktype: int, is_siteroot: bool}>
     */
    private function findUsagePagesForFragment(int $fragmentUid, ?array $accessiblePageIds, int $maxPagesShown): array
    {
        $qb = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
        $qb->getRestrictions()
            ->removeByType(HiddenRestriction::class)
            ->removeByType(StartTimeRestriction::class)
            ->removeByType(EndTimeRestriction::class)
            ->add(GeneralUtility::makeInstance(WorkspaceRestriction::class, 0));
        $qb->distinct()
            ->select(
                self::PAGES_TABLE . '.uid',
                self::PAGES_TABLE . '.pid',
                self::PAGES_TABLE . '.title',
                self::PAGES_TABLE . '.hidden',
                self::PAGES_TABLE . '.doktype',
                self::PAGES_TABLE . '.is_siteroot',
                self::PAGES_TABLE . '.starttime',
                self::PAGES_TABLE . '.endtime',
                self::PAGES_TABLE . '.nav_hide',
                self::PAGES_TABLE . '.fe_group',
                self::PAGES_TABLE . '.module',
                self::PAGES_TABLE . '.content_from_pid',
            )
            ->from(self::ASSIGNMENT_TABLE)
            ->innerJoin(
                self::ASSIGNMENT_TABLE,
                self::PAGES_TABLE,
                self::PAGES_TABLE,
                $qb->expr()->eq(self::PAGES_TABLE . '.uid', $qb->quoteIdentifier(self::ASSIGNMENT_TABLE . '.parent_page')),
            )
            ->where($qb->expr()->eq(self::ASSIGNMENT_TABLE . '.fragment', $qb->createNamedParameter($fragmentUid, Connection::PARAM_INT)))
            ->orderBy(self::PAGES_TABLE . '.title', 'asc')
            ->addOrderBy(self::PAGES_TABLE . '.uid', 'asc')
            ->setMaxResults($maxPagesShown);

        if ($accessiblePageIds !== null) {
            $qb->andWhere($qb->expr()->in(
                self::ASSIGNMENT_TABLE . '.parent_page',
                $qb->createNamedParameter($accessiblePageIds, Connection::PARAM_INT_ARRAY),
            ));
        }

        $pages = [];
        foreach ($qb->executeQuery()->fetchAllAssociative() as $row) {
            $pages[] = [
                'uid' => (int)$row['uid'],
                'pid' => (int)$row['pid'],
                'title' => (string)$row['title'],
                'hidden' => (bool)$row['hidden'],
                'doktype' => (int)$row['doktype'],
                'is_siteroot' => (bool)$row['is_siteroot'],
                'starttime' => (int)$row['starttime'],
                'endtime' => (int)$row['endtime'],
                'nav_hide' => (bool)$row['nav_hide'],
                'fe_group' => (string)$row['fe_group'],
                'module' => (string)$row['module'],
                'content_from_pid' => (int)$row['content_from_pid'],
            ];
        }
        return $pages;
    }

    /**
     * @param list<int>|null $accessiblePageIds
     * @param list<int>|null $usagePageIds Page-tree selection filter (see
     *   PromptManagementController::renderLibraryView()'s docblock):
     *   restricts to fragments actually ASSIGNED somewhere in these pages,
     *   via a separate EXISTS-style subquery against the assignment table -
     *   deliberately not folded into the $accessiblePageIds OR-clause below,
     *   which answers a different question (is this fragment's own storage
     *   pid one the user may reach at all). A global (pid=0) fragment is
     *   exempt from both: always visible regardless of tree selection.
     */
    private function getLibraryQueryBuilderForDemand(PagePromptFragmentDemand $demand, ?array $accessiblePageIds, ?array $usagePageIds = null): QueryBuilder
    {
        $qb = $this->connectionPool->getQueryBuilderForTable(self::FRAGMENT_TABLE);
        $qb->getRestrictions()
            ->removeAll()
            ->add(GeneralUtility::makeInstance(DeletedRestriction::class))
            ->add(GeneralUtility::makeInstance(WorkspaceRestriction::class, 0));
        $qb->from(self::FRAGMENT_TABLE);

        if ($demand->hasScope() && $demand->getScope() !== PromptFragmentScope::All) {
            $qb->andWhere($qb->expr()->or(
                $qb->expr()->inSet('scope', $qb->quote(PromptFragmentScope::All->value)),
                $qb->expr()->inSet('scope', $qb->quote($demand->getScope()->value)),
            ));
        }

        if ($demand->hasSearch()) {
            $escaped = '%' . $qb->escapeLikeWildcards($demand->getSearch()) . '%';
            $qb->andWhere($qb->expr()->or(
                $qb->expr()->like('prompt', $qb->createNamedParameter($escaped)),
                $qb->expr()->like('examples', $qb->createNamedParameter($escaped)),
                $qb->expr()->like('title', $qb->createNamedParameter($escaped)),
            ));
        }

        if ($accessiblePageIds !== null) {
            $qb->andWhere($qb->expr()->or(
                $qb->expr()->eq('pid', $qb->createNamedParameter(0, Connection::PARAM_INT)),
                $qb->expr()->in('pid', $qb->createNamedParameter($accessiblePageIds, Connection::PARAM_INT_ARRAY)),
            ));
        }

        if ($usagePageIds !== null) {
            $usageSubQuery = $this->connectionPool->getQueryBuilderForTable(self::ASSIGNMENT_TABLE);
            $usageSubQuery->getRestrictions()->add(GeneralUtility::makeInstance(WorkspaceRestriction::class, 0));
            $usageSubQuery->select('fragment')
                ->from(self::ASSIGNMENT_TABLE)
                ->where($qb->expr()->in(
                    'parent_page',
                    $qb->createNamedParameter($usagePageIds, Connection::PARAM_INT_ARRAY),
                ));
            $qb->andWhere($qb->expr()->or(
                $qb->expr()->eq('pid', $qb->createNamedParameter(0, Connection::PARAM_INT)),
                $qb->expr()->in('uid', $usageSubQuery->getSQL()),
            ));
        }

        return $qb;
    }
}
