services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Aim\:
    resource: '../Classes/*'
    exclude: '../Classes/Provider/SymfonyAi/*'

  B13\Aim\Domain\Repository\ProviderConfigurationRepository:
    public: true
